server {
    listen 80;
    server_name agriconnect.gleeze.com;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}